export async function up(
  sql: (arg: TemplateStringsArray) => Promise<string[]>,
) {
  console.log('Creating employee_sessions table...');
  await sql`

CREATE TABLE employee_sessions(
id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
token varchar(90) NOT NULL,
expiry_timestamp timestamp NOT NULL DEFAULT NOW() + INTERVAL '24 hours',
employee_id integer REFERENCES employees (id) ON DELETE CASCADE
);
	`;
}

export async function down(
  sql: (arg: TemplateStringsArray) => Promise<string[]>,
) {
  console.log('Dropping employee_sessions table');
  await sql`

	DROP TABLE employee_sessions;

	`;
}
