export async function up(
  sql: (arg: TemplateStringsArray) => Promise<string[]>,
) {
  console.log('Creating customer_sessions table...');
  await sql`

CREATE TABLE customer_sessions(
id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
token varchar(90) NOT NULL,
expiry_timestamp timestamp NOT NULL DEFAULT NOW() + INTERVAL '24 hours',
customer_id integer REFERENCES customers (id) ON DELETE CASCADE
);
	`;
}

export async function down(
  sql: (arg: TemplateStringsArray) => Promise<string[]>,
) {
  console.log('Dropping customer_sessions table');
  await sql`

	DROP TABLE customer_sessions;

	`;
}
